config/routes.rb
Rails.application.routes.draw do

  get 'users/new'
  get 'users/index'


  get 'courses/new'
  get 'courses/edit'
  get 'courses/index'
  get 'courses/show'

  get 'cohorts/new'
  get 'cohorts/edit'
  get 'cohorts/show'
  get 'cohorts/index'


  get 'students/new'
  get 'students/index'
  get 'students/edit'
  get 'students/show'

  resources :users


  resources :courses do
    resources :cohorts do
      resources :instructors
      resources :students
    end
  end

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
delete '/logout' => 'sessions#destroy'

  root 'pages#home'
  get 'instructors/new'
  get 'instructors/index'
  get 'instructors/edit'
  get 'instructors/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class = "nav">
  <div class="logo">
  </div>
  <div class = 'nav_icon'><i class="fas fa-home"><%=link_to 'Home', root_path%></i></div>
  <% if logged_in?%>
    <div class="nav_icon"><i class="fas fa-chalkboard-teacher"><%=link_to 'Instructors', instructors_index_path%></i></div>
    <% if current_user.student != true%>
    <div class="nav_icon"><i class="fas fa-user-graduate"><%= link_to 'Students', students_index_path%></i></div>
    <%end%>
    <% if current_user.admin === true %>
      <div class="nav_icon"><i class="fas fa-users"><%=link_to 'Users', users_index_path%></i></div>
      <% else%>
      <div class="nav_icon"><i class="fas fa-book"><%=link_to 'Courses', courses_index_path%></i></div>
      <div class="nav_icon"><i class="fas fa-school" ><%=link_to 'Cohorts', cohorts_index_path%></i></div>
    <%end%>
    <div class='nav_icon'><i class="fas fa-sign-out-alt"><%= link_to 'Log Out',logout_path, method: :delete%></i></div>
  <%else%>
  <div class = 'nav_icon'><i class="fas fa-sign-in-alt"><%=link_to 'Log In', login_path%></i></div>
  <div class ='nav_icon' ><i class="fas fa-user-plus"><%=link_to 'Sign Up', users_new_path%></i></div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <div class="header">
        <h1 id='dashboard'><%= link_to 'Dashboard'%></h1>
      </div>

      <%= render 'layouts/header'%>
      <div class="main-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>